/**:
  estop:
    ros__parameters:
      time_step_size: 0.02

  stand:
    ros__parameters:
      time_step_size: 0.02
      duration: 1.0

  controller:
  # py_controller:
    ros__parameters:
      time_step_size: 0.002

  comm:
    ros__parameters:
      time_step_size: 0.01
      monitorPublisherQueueSize: 10
      remoteSubscriberQueueSize: 10

  robot:
    ros__parameters:
      time_step_size: 0.001667  # sim rate
      robot_xml_file: "g1_description/scene_crl.xml"
