/**:
  estop:
    ros__parameters:
      time_step_size: 0.02

  stand:
    ros__parameters:
      time_step_size: 0.02
      duration: 1.0

  walk:
    ros__parameters:
      time_step_size: 0.01667
      robot_controllers_policy_file: "/models/tron1a_walk/policy.onnx"
      robot_controllers_encoder_file: "/models/tron1a_walk/encoder.onnx"
      # model: "/models/g1_walk_v2/g1_walk_config.json"

  comm:
    ros__parameters:
      time_step_size: 0.01
      monitorPublisherQueueSize: 10
      remoteSubscriberQueueSize: 10

  robot:
    ros__parameters:
      time_step_size: 0.001667  # sim rate
      robot_xml_file: "tron1a_description/scene_crl.xml"
      joystick_max_forward_velocity: 0.8   # Maximum forward walking speed
      joystick_max_backward_velocity: 0.8  # Maximum backward walking speed
      joystick_max_sideways_velocity: 0.3  # Maximum sideways walking speed
      joystick_max_turning_velocity: 1.0   # Maximum turning speed
      # joystick_max_forward_velocity: 1.5   # Maximum forward walking speed
      # joystick_max_backward_velocity: 1.0  # Maximum backward walking speed
      # joystick_max_sideways_velocity: 0.5  # Maximum sideways walking speed
      # joystick_max_turning_velocity: 1.0   # Maximum turning speed

