/**:
  estop:
    ros__parameters:
      time_step_size: 0.02

  stand:
    ros__parameters:
      time_step_size: 0.02
      duration: 1.0
      loop_frequency: 500.0  # Control loop frequency for stand-up interpolation


  walk:
    ros__parameters:
      time_step_size: 0.002  # 500 Hz to match loop_frequency in deployment (1/500.0 = 0.002)
      robot_controllers_policy_file: "/home/nathan_lacour/CRL_Humanoid/crl-humanoid-ros/crl_tron1a_rlcontroller/data/models/tron1a_walk/policy.onnx"
      robot_controllers_encoder_file: "/home/nathan_lacour/CRL_Humanoid/crl-humanoid-ros/crl_tron1a_rlcontroller/data/models/tron1a_walk/encoder.onnx"
      
      # RL-specific controller parameters
      # Note: Default joint angles, stiffness, damping, and wheel joint parameters are set directly from RobotParameters.h
      # Control parameters
      action_scale_pos: 0.25
      decimation: 10  # Matches deployment config but not training config (was 4)
      user_torque_limit: 80.0
      
      # Normalization parameters
      obs_scale_lin_vel: 2.0
      obs_scale_ang_vel: 0.25
      obs_scale_dof_pos: 1.0
      obs_scale_dof_vel: 0.05
      clip_actions: 100.0
      clip_observations: 100.0
      
      # Model size parameters
      actions_size: 8
      observations_size: 28
      obs_history_length: 10
      encoder_output_size: 3
      
      # IMU orientation offset
      imu_offset_yaw: 0.0
      imu_offset_pitch: 0.0
      imu_offset_roll: 0.0
      
      # User command scales
      cmd_scale_lin_vel_x: 1.5
      cmd_scale_lin_vel_y: 1.0
      cmd_scale_ang_vel_yaw: 0.5

  comm:
    ros__parameters:
      time_step_size: 0.01
      monitorPublisherQueueSize: 10
      remoteSubscriberQueueSize: 10

  robot:
    ros__parameters:
      time_step_size: 0.002 #0.001667  # sim rate
      robot_xml_file: "wf_tron1a_description/xml/scene_crl.xml"
      joystick_max_forward_velocity: 0.8   # Maximum forward walking speed
      joystick_max_backward_velocity: 0.8  # Maximum backward walking speed
      joystick_max_sideways_velocity: 0.3  # Maximum sideways walking speed
      joystick_max_turning_velocity: 1.0   # Maximum turning speed
      # Elastic band parameters (adjust target_height to lower the band)
      elastic_band_enabled: true
      elastic_band_stiffness: 5000.0 # 1000.0 before     # N/m
      elastic_band_damping: 100.0    # Ns/m
      elastic_band_target_height: 0.9 #1.1 before   # m (lowered from default 1.45m)
      # joystick_max_forward_velocity: 1.5   # Maximum forward walking speed
      # joystick_max_backward_velocity: 1.0  # Maximum backward walking speed
      # joystick_max_sideways_velocity: 0.5  # Maximum sideways walking speed
      # joystick_max_turning_velocity: 1.0   # Maximum turning speed

